---
- hosts: web
  remote_user: ubuntu
  become: yes
  tasks:
  - name: "Validate whether python3 exists on Managed node"
    command: which python3
    register: result

  - name: "Install Ansible as python exists"
    apt:
      name: ansible
      state: present
    when: result.rc == 0
...
