---
- hosts: localhost
  #remote_user: ubuntu
  tasks:
  - name: Check Ansible version
    command: ansible --version
    register: ansibleVersion

  - name: Print version
    debug:
      msg: "Ansible Version: {{ ansibleVersion.stdout }}"
    delegate_to: localhost
...
